// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/sensor.proto

package iot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure      float64                `protobuf:"fixed64,5,opt,name=pressure,proto3" json:"pressure,omitempty"`
	BatteryLevel  float64                `protobuf:"fixed64,6,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_api_proto_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReading) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorReading) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorReading) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorReading) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *SensorReading) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

type GetSensorReadingByDeviceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSensorReadingByDeviceIDRequest) Reset() {
	*x = GetSensorReadingByDeviceIDRequest{}
	mi := &file_api_proto_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSensorReadingByDeviceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSensorReadingByDeviceIDRequest) ProtoMessage() {}

func (x *GetSensorReadingByDeviceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSensorReadingByDeviceIDRequest.ProtoReflect.Descriptor instead.
func (*GetSensorReadingByDeviceIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *GetSensorReadingByDeviceIDRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetSensorReadingByDeviceIDRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetSensorReadingByDeviceIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       []*SensorReading       `protobuf:"bytes,1,rep,name=reading,proto3" json:"reading,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSensorReadingByDeviceIDResponse) Reset() {
	*x = GetSensorReadingByDeviceIDResponse{}
	mi := &file_api_proto_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSensorReadingByDeviceIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSensorReadingByDeviceIDResponse) ProtoMessage() {}

func (x *GetSensorReadingByDeviceIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSensorReadingByDeviceIDResponse.ProtoReflect.Descriptor instead.
func (*GetSensorReadingByDeviceIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *GetSensorReadingByDeviceIDResponse) GetReading() []*SensorReading {
	if x != nil {
		return x.Reading
	}
	return nil
}

func (x *GetSensorReadingByDeviceIDResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type IoTDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Firmware      string                 `protobuf:"bytes,6,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Latitude      float32                `protobuf:"fixed32,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoTDevice) Reset() {
	*x = IoTDevice{}
	mi := &file_api_proto_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoTDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoTDevice) ProtoMessage() {}

func (x *IoTDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoTDevice.ProtoReflect.Descriptor instead.
func (*IoTDevice) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *IoTDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IoTDevice) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IoTDevice) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *IoTDevice) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *IoTDevice) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *IoTDevice) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *IoTDevice) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *IoTDevice) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetAllDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*IoTDevice           `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDevicesResponse) Reset() {
	*x = GetAllDevicesResponse{}
	mi := &file_api_proto_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDevicesResponse) ProtoMessage() {}

func (x *GetAllDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllDevicesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllDevicesResponse) GetDevices() []*IoTDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetAllDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDevicesRequest) Reset() {
	*x = GetAllDevicesRequest{}
	mi := &file_api_proto_sensor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDevicesRequest) ProtoMessage() {}

func (x *GetAllDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetAllDevicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{5}
}

type GetDeviceByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByIDRequest) Reset() {
	*x = GetDeviceByIDRequest{}
	mi := &file_api_proto_sensor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByIDRequest) ProtoMessage() {}

func (x *GetDeviceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeviceByIDRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *IoTDevice             `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByIDResponse) Reset() {
	*x = GetDeviceByIDResponse{}
	mi := &file_api_proto_sensor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByIDResponse) ProtoMessage() {}

func (x *GetDeviceByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByIDResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceByIDResponse) GetDevice() *IoTDevice {
	if x != nil {
		return x.Device
	}
	return nil
}

var File_api_proto_sensor_proto protoreflect.FileDescriptor

const file_api_proto_sensor_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/sensor.proto\x12\x03iot\"\xc9\x01\n" +
	"\rSensorReading\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x01R\bhumidity\x12\x1a\n" +
	"\bpressure\x18\x05 \x01(\x01R\bpressure\x12#\n" +
	"\rbattery_level\x18\x06 \x01(\x01R\fbatteryLevel\"_\n" +
	"!GetSensorReadingByDeviceIDRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"z\n" +
	"\"GetSensorReadingByDeviceIDResponse\x12,\n" +
	"\areading\x18\x01 \x03(\v2\x12.iot.SensorReadingR\areading\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xf8\x01\n" +
	"\tIoTDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bfirmware\x18\x06 \x01(\tR\bfirmware\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x02R\tlongitude\"A\n" +
	"\x15GetAllDevicesResponse\x12(\n" +
	"\adevices\x18\x01 \x03(\v2\x0e.iot.IoTDeviceR\adevices\"\x16\n" +
	"\x14GetAllDevicesRequest\"3\n" +
	"\x14GetDeviceByIDRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"?\n" +
	"\x15GetDeviceByIDResponse\x12&\n" +
	"\x06device\x18\x01 \x01(\v2\x0e.iot.IoTDeviceR\x06device2\x8c\x02\n" +
	"\n" +
	"IoTService\x12G\n" +
	"\fGetAllDevice\x12\x19.iot.GetAllDevicesRequest\x1a\x1a.iot.GetAllDevicesResponse\"\x00\x12D\n" +
	"\tGetDevice\x12\x19.iot.GetDeviceByIDRequest\x1a\x1a.iot.GetDeviceByIDResponse\"\x00\x12o\n" +
	"\x1aGetSensorReadingByDeviceID\x12&.iot.GetSensorReadingByDeviceIDRequest\x1a'.iot.GetSensorReadingByDeviceIDResponse\"\x00B\x1fZ\x1dprocodus.dev/demo-app/pkg/iotb\x06proto3"

var (
	file_api_proto_sensor_proto_rawDescOnce sync.Once
	file_api_proto_sensor_proto_rawDescData []byte
)

func file_api_proto_sensor_proto_rawDescGZIP() []byte {
	file_api_proto_sensor_proto_rawDescOnce.Do(func() {
		file_api_proto_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sensor_proto_rawDesc), len(file_api_proto_sensor_proto_rawDesc)))
	})
	return file_api_proto_sensor_proto_rawDescData
}

var file_api_proto_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_sensor_proto_goTypes = []any{
	(*SensorReading)(nil),                      // 0: iot.SensorReading
	(*GetSensorReadingByDeviceIDRequest)(nil),  // 1: iot.GetSensorReadingByDeviceIDRequest
	(*GetSensorReadingByDeviceIDResponse)(nil), // 2: iot.GetSensorReadingByDeviceIDResponse
	(*IoTDevice)(nil),                          // 3: iot.IoTDevice
	(*GetAllDevicesResponse)(nil),              // 4: iot.GetAllDevicesResponse
	(*GetAllDevicesRequest)(nil),               // 5: iot.GetAllDevicesRequest
	(*GetDeviceByIDRequest)(nil),               // 6: iot.GetDeviceByIDRequest
	(*GetDeviceByIDResponse)(nil),              // 7: iot.GetDeviceByIDResponse
}
var file_api_proto_sensor_proto_depIdxs = []int32{
	0, // 0: iot.GetSensorReadingByDeviceIDResponse.reading:type_name -> iot.SensorReading
	3, // 1: iot.GetAllDevicesResponse.devices:type_name -> iot.IoTDevice
	3, // 2: iot.GetDeviceByIDResponse.device:type_name -> iot.IoTDevice
	5, // 3: iot.IoTService.GetAllDevice:input_type -> iot.GetAllDevicesRequest
	6, // 4: iot.IoTService.GetDevice:input_type -> iot.GetDeviceByIDRequest
	1, // 5: iot.IoTService.GetSensorReadingByDeviceID:input_type -> iot.GetSensorReadingByDeviceIDRequest
	4, // 6: iot.IoTService.GetAllDevice:output_type -> iot.GetAllDevicesResponse
	7, // 7: iot.IoTService.GetDevice:output_type -> iot.GetDeviceByIDResponse
	2, // 8: iot.IoTService.GetSensorReadingByDeviceID:output_type -> iot.GetSensorReadingByDeviceIDResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_sensor_proto_init() }
func file_api_proto_sensor_proto_init() {
	if File_api_proto_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sensor_proto_rawDesc), len(file_api_proto_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sensor_proto_goTypes,
		DependencyIndexes: file_api_proto_sensor_proto_depIdxs,
		MessageInfos:      file_api_proto_sensor_proto_msgTypes,
	}.Build()
	File_api_proto_sensor_proto = out.File
	file_api_proto_sensor_proto_goTypes = nil
	file_api_proto_sensor_proto_depIdxs = nil
}
