// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/sensor.proto

package iot

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure      float64                `protobuf:"fixed64,5,opt,name=pressure,proto3" json:"pressure,omitempty"`
	BatteryLevel  float64                `protobuf:"fixed64,6,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_api_proto_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReading) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorReading) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorReading) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorReading) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *SensorReading) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

var File_api_proto_sensor_proto protoreflect.FileDescriptor

const file_api_proto_sensor_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/sensor.proto\x12\x03iot\"\xc9\x01\n" +
	"\rSensorReading\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x01R\bhumidity\x12\x1a\n" +
	"\bpressure\x18\x05 \x01(\x01R\bpressure\x12#\n" +
	"\rbattery_level\x18\x06 \x01(\x01R\fbatteryLevelB\x1fZ\x1dprocodus.dev/demo-app/pkg/iotb\x06proto3"

var (
	file_api_proto_sensor_proto_rawDescOnce sync.Once
	file_api_proto_sensor_proto_rawDescData []byte
)

func file_api_proto_sensor_proto_rawDescGZIP() []byte {
	file_api_proto_sensor_proto_rawDescOnce.Do(func() {
		file_api_proto_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sensor_proto_rawDesc), len(file_api_proto_sensor_proto_rawDesc)))
	})
	return file_api_proto_sensor_proto_rawDescData
}

var file_api_proto_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_sensor_proto_goTypes = []any{
	(*SensorReading)(nil), // 0: iot.SensorReading
}
var file_api_proto_sensor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_sensor_proto_init() }
func file_api_proto_sensor_proto_init() {
	if File_api_proto_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sensor_proto_rawDesc), len(file_api_proto_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_sensor_proto_goTypes,
		DependencyIndexes: file_api_proto_sensor_proto_depIdxs,
		MessageInfos:      file_api_proto_sensor_proto_msgTypes,
	}.Build()
	File_api_proto_sensor_proto = out.File
	file_api_proto_sensor_proto_goTypes = nil
	file_api_proto_sensor_proto_depIdxs = nil
}
